export enum ConversationState {
  MENU = 'MENU',
  SHOW_MODELS = 'SHOW_MODELS',
  SHOW_DYNAMICS = 'SHOW_DYNAMICS',
  SHOW_DELIVERY = 'SHOW_DELIVERY',
  SHOW_LOCATION = 'SHOW_LOCATION',
  SHOW_HOW_TO_BUY = 'SHOW_HOW_TO_BUY',
  POST_INFO_MENU = 'POST_INFO_MENU',
  CAPTURE_QUOTE_DATA = 'CAPTURE_QUOTE_DATA',
  OPEN_QUESTION = 'OPEN_QUESTION',
  WAITING_HUMAN = 'WAITING_HUMAN',
  HUMAN_HANDOFF = 'HUMAN_HANDOFF',
}
